version: '3.8'
services:
  petfinder-container:
    image: mysql:8
    container_name: petfinder-container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_NAME:-ADOPTION_SYS}
      MYSQL_USER: ${DB_USER:-user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-1234}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/cmd/bbdd:/docker-entrypoint-initdb.d
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=development
    depends_on:
      - petfinder-container
    restart: unless-stopped
    command: ["go", "run", "main.go"]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend:/app/frontend
      - ./frontend/proxy.conf.json:/app/frontend/proxy.conf.json
      - node_modules:/app/frontend/node_modules
    ports:
      - "4200:4200"
    depends_on:
      - backend
    command: ["ng", "serve", "--host", "0.0.0.0", "--proxy-config", "proxy.conf.json"]
    restart: unless-stopped
    
volumes:
  mysql_data:
  node_modules:
