FROM node:20-alpine

WORKDIR /app/frontend

WORKDIR /app/frontend

COPY package*.json ./
RUN npm install -g @angular/cli
RUN npm install --legacy-peer-deps

COPY . .

EXPOSE 4200

CMD ["ng", "serve", "--host", "0.0.0.0", "--proxy-config", "proxy.config.json"]